#!/usr/bin/env node
// vendor.mjs — copies the exact extension modules the Control Panel depends
// on into control-panel/vendor/, so the packaged desktop app ships with the
// SAME merge/crypto/provider code the browser extension runs, instead of a
// hand-maintained duplicate that could quietly drift out of sync.
//
// Why copy at all, instead of importing "../../bookmarks/lib/tree.js"
// straight from the repo? Because electron-builder only packages files that
// live inside control-panel/ (see package.json "build.files") — anything
// referenced by a path that climbs out of this folder simply isn't there on
// a machine that only received the installed app. Vendoring makes the
// dependency explicit and keeps "what we tested" identical to "what ships".
//
// Run automatically before `npm start`, `npm test` and `npm run dist:win`
// (see package.json's pre* hooks) — never edit anything under vendor/ by
// hand, it is overwritten on every run.

import { mkdir, copyFile, writeFile, readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const here = path.dirname(fileURLToPath(import.meta.url));
const CP_ROOT = path.resolve(here, '..');
const REPO_ROOT = path.resolve(CP_ROOT, '..');
const VENDOR = path.join(CP_ROOT, 'vendor');

// [sourceRelativeToRepoRoot, destRelativeToVendor]
const FILES = [
  ['bookmarks/lib/tree.js', 'bookmarks-lib/tree.js'],
  ['bookmarks/lib/merge.js', 'bookmarks-lib/merge.js'],
  ['bookmarks/lib/crypto.js', 'bookmarks-lib/crypto.js'],
  ['bookmarks/lib/bookmarks-io.js', 'bookmarks-lib/bookmarks-io.js'],
  ['bookmarks/lib/sync.js', 'bookmarks-lib/sync.js'],
  ['shared/providers.js', 'shared/providers.js'],
  ['tabs/storage.js', 'tabs/storage.js'],
];

function gitInfo() {
  try {
    const rev = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: REPO_ROOT }).toString().trim();
    const dirty = execFileSync('git', ['status', '--porcelain', '--', ...FILES.map((f) => f[0])], { cwd: REPO_ROOT })
      .toString().trim().length > 0;
    return { rev, dirty };
  } catch {
    return { rev: 'unknown', dirty: false };
  }
}

async function main() {
  for (const [src, dest] of FILES) {
    const srcPath = path.join(REPO_ROOT, src);
    const destPath = path.join(VENDOR, dest);
    if (!existsSync(srcPath)) {
      throw new Error(`vendor.mjs: expected source file missing: ${src} — did it move? Update scripts/vendor.mjs's FILES list.`);
    }
    await mkdir(path.dirname(destPath), { recursive: true });
    await copyFile(srcPath, destPath);
  }

  const { rev, dirty } = gitInfo();
  const manifest = {
    generatedAt: new Date().toISOString(),
    sourceCommit: rev + (dirty ? ' (with local changes)' : ''),
    files: FILES.map(([src, dest]) => ({ src, dest })),
    note: 'Generated by control-panel/scripts/vendor.mjs — do not edit files under vendor/ by hand, re-run `npm run vendor` instead.',
  };
  await writeFile(path.join(VENDOR, 'MANIFEST.json'), JSON.stringify(manifest, null, 2) + '\n');

  console.log(`[vendor] copied ${FILES.length} files from ${REPO_ROOT} (commit ${manifest.sourceCommit}) into ${VENDOR}`);
}

main().catch((e) => {
  console.error('[vendor] failed:', e.message);
  process.exit(1);
});
